version: '3'

services:
  app:
    build:
      context: docker/app
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
    ports:
      - '8000:8000'
    links:
      - db
  db:
    image: mysql:5.7.4
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app_db
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    ports:
      - '3306:3306'